---
title: "Writing Functions"
author: "Ruijie He"
date: "2023-11-09"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Do something simple

```{r}
x_vec = rnorm(30, mean = 5, sd = 3) # Input data of the function

(x_vec - mean(x_vec)) / sd(x_vec)
```

I want a **function** to compute z-score

```{r}
z_scores = function(x) { # Setting z-score equal to a whole function instead of computation
  
  if(!is.numeric(x)) {
    stop("Input must be numeric") # Stop with the error message in ""
  } # If statement to set numeric number only
  
  if(length(x)  < 3) {
    stop("Input must have at least three numbers")
  }
  
  z = (x - mean(x)) / sd(x) # Return objects
 
   return(z)
  
} # The body of the function

z_scores(x_vec)
```

Try my function on some other things (these should give errors)

```{r, error = TRUE}
z_scores(3)
z_scores("my name is jeff") # Cannot take mean of non-numerical data
z_scores(mtcars) # Cannot take mean of a dataset
z_scores(c(TRUE, TRUE, FALSE, TRUE))
```

## Multipleoutputs

```{r}
mean_and_sd = function(x) {
  
  if(!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if(length(x)  < 3) {
    stop("Input must have at least three numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
# Organize the multiple outputs
  
  tibble( #Make these output a daat frame
    mean = mean_x,
    sd = sd_x
  )
  
}
```

Check out the functions

```{r}
x_vec = rnorm(100, mean = 3, sd = 4) # Creating new vector
mean_and_sd(x_vec)
```
## Multiple inputs

I'd like to do this with a function

```{r}
sim_data = # Simulated dataset
  tibble(
    x = rnorm(n = 100, mean = 4, sd = 3)
  ) # Create data frame

sim_data %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  ) # Give the data frame computations of mean and sd
```

Translate the above into functions

```{r}
sim_mean_sd = function(sample_size, mu = 3, sigma = 4) {# Three inputs with given default value
  sim_data = # Simulated dataset
  tibble(
    x = rnorm(n = sample_size, mean = mu, sd = sigma)
  )
  
  sim_data %>% 
    summarize(
      mean = mean(x),
      sd = sd(x)
      )
} # Body of function

sim_mean_sd(sample_size = 100, mu = 6, sigma = 3) # Positional matching
sim_mean_sd(mu = 6, sample_size = 100, sigma = 3) # The new value will overwrite the defalut value
```

